<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>Bannerlord.NativeCharacterImageGenerator.SourceCacheVerifier</AssemblyName>
    <RootNamespace>Bannerlord.NativeCharacterImageGenerator.SourceCacheVerifier</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NativeCharacterImageGenerator\NativeCharacterImageGenerator.csproj" />
    <ProjectReference Include="..\NativeCharacterImageGenerator.App\NativeCharacterImageGenerator.App.csproj" />
  </ItemGroup>
</Project>
